import { AdminShell, EmptyState } from "../../../admin-shell";
import { recordContentReviewAction } from "../../../actions";
import { getContentReviewQueue, resolveAdminTenant } from "../../../data";

type ReviewPageProps = {
  searchParams: Promise<{ tenant?: string }>;
};

const checklistItems = [
  ["no_guarantees", "No guarantees"],
  ["no_product_recommendation", "No product recommendation"],
  ["no_advisor_identity", "No advisor identity"],
  ["disclosure_present", "Disclosure present"],
  ["sources_present", "Sources present"],
  ["cta_educational", "CTA educational"]
] as const;

export default async function ContentReviewPage({ searchParams }: ReviewPageProps) {
  const params = await searchParams;
  const tenant = resolveAdminTenant(params.tenant ?? "retire-ready-mn");
  const queue = await getContentReviewQueue(tenant);

  return (
    <AdminShell selectedTenantSlug={tenant.identity.slug}>
      <section>
        <h2>Compliance Review Checklist</h2>
        <p>Publishing should remain blocked until every educational-content item is checked.</p>
        {queue.status === "unavailable" ? (
          <EmptyState title="Review queue unavailable" body={queue.reason} />
        ) : queue.data.drafts.length === 0 ? (
          <EmptyState title="No drafts in review" body="Drafts generated by the content workflow will appear here." />
        ) : (
          <div className="content-review-list">
            {queue.data.drafts.map((draft) => (
              <article key={draft.id} className="content-review-card">
                <div>
                  <span>{draft.category}</span>
                  <h3>{draft.title}</h3>
                  <p>
                    {draft.slug} · {draft.status} · {draft.compliance_status} · {String(draft.word_count)} words
                  </p>
                </div>
                <form action={recordContentReviewAction} className="content-review-form">
                  <input type="hidden" name="tenantSlug" value={tenant.identity.slug} />
                  <input type="hidden" name="draftId" value={draft.id} />
                  <label>
                    <span>Reviewer</span>
                    <input name="reviewer" defaultValue="internal-compliance" />
                  </label>
                  <fieldset>
                    <legend>Checklist</legend>
                    {checklistItems.map(([name, label]) => (
                      <label key={name} className="check-row">
                        <input type="checkbox" name={name} />
                        <span>{label}</span>
                      </label>
                    ))}
                  </fieldset>
                  <label>
                    <span>Publication status</span>
                    <select name="publicationStatus" defaultValue={draft.status}>
                      <option value="draft">Draft</option>
                      <option value="review">Needs review</option>
                      <option value="published">Published</option>
                    </select>
                  </label>
                  <textarea name="notes" placeholder="Review notes" />
                  <button type="submit">Record review</button>
                </form>
              </article>
            ))}
          </div>
        )}
      </section>

      <section>
        <h2>Open Compliance Flags</h2>
        {queue.status === "ready" && queue.data.flags.length > 0 ? (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Type</th>
                  <th>Severity</th>
                  <th>Message</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
                {queue.data.flags.map((flag) => (
                  <tr key={flag.id}>
                    <td>{flag.flag_type}</td>
                    <td>{flag.severity}</td>
                    <td>{flag.message}</td>
                    <td>{flag.created_at}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <EmptyState title="No open flags" body="Checklist misses will create blocking flags for follow-up." />
        )}
      </section>
    </AdminShell>
  );
}
